#ifndef JSTR_CONFIG_DEF_H
#define JSTR_CONFIG_DEF_H

#define JSTR_MAX_UINT_DIGITS	   10
#define JSTR_MAX_ULONG_DIGITS	   10
#define JSTR_MAX_ULONG_LONG_DIGITS 19

#define JSTR_MAX_INT_DIGITS	  (JSTR_MAX_UINT_DIGITS + 1)
#define JSTR_MAX_LONG_DIGITS	  (JSTR_MAX_ULONG_DIGITS + 1)
#define JSTR_MAX_LONG_LONG_DIGITS (JSTR_MAX_ULONG_LONG_DIGITS + 1)

#define PJSTR_MIN_MMAP (128 * 1024)

#define JSTR_MIN_CAP ((sizeof(size_t) == 8) ? 24 : 16)

#ifndef PJARR_GROWTH
#	define PJARR_GROWTH 1.5
#endif

#ifndef JSTR_HAVE_ALLOCA
#	define JSTR_HAVE_ALLOCA 1
#endif

#ifndef JSTR_GROWTH_MULTIPLIER
#	define JSTR_GROWTH_MULTIPLIER 1.5
#endif

#ifndef JSTR_ALLOC_MULTIPLIER
#	define JSTR_ALLOC_MULTIPLIER 2
#endif

#ifndef JSTR_EXIT_ON_MALLOC_ERROR
#	define JSTR_EXIT_ON_MALLOC_ERROR 1
#endif

#ifndef JSTR_PRINT_ERR_MSG_ON_MALLOC_ERROR
#	define JSTR_PRINT_ERR_MSG_ON_MALLOC_ERROR 1
#endif

#ifndef JSTR_PRINT_ERR_MSG_ON_REGEX_ERROR
#	define JSTR_PRINT_ERR_MSG_ON_REGEX_ERROR 1
#endif

#ifndef JSTR_FREE_ON_DESTRUCTOR_CPP
#	define JSTR_FREE_ON_DESTRUCTOR_CPP 1
#endif

#ifndef JSTR_NULLIFY_PTR_ON_DESTRUCTOR_CPP
#	define JSTR_NULLIFY_PTR_ON_DESTRUCTOR_CPP 1
#endif

#ifndef JSTR_NULLIFY_PTR_ON_DELETE
#	define JSTR_NULLIFY_PTR_ON_DELETE 1
#endif

#if JSTR_FREE_ON_DESTRUCTOR_CPP
#	undef JSTR_NULLIFY_PTR_ON_DELETE
#	define JSTR_NULLIFY_PTR_ON_DELETE 1
#endif

#ifndef JSTR_GROWTH_MULTIPLIER
#	define JSTR_GROWTH_MULTIPLIER 2
#endif

#endif /* JSTR_CONFIG_DEF_H */
