#ifndef JSTR_CONFIG_DEF_H
#define JSTR_CONFIG_DEF_H

#define JSTR_MAX_UINT_DIGITS	   10
#define JSTR_MAX_ULONG_DIGITS	   10
#define JSTR_MAX_ULONG_LONG_DIGITS 19

#define JSTR_MAX_INT_DIGITS	  (JSTR_MAX_UINT_DIGITS + 1)
#define JSTR_MAX_LONG_DIGITS	  (JSTR_MAX_ULONG_DIGITS + 1)
#define JSTR_MAX_LONG_LONG_DIGITS (JSTR_MAX_ULONG_LONG_DIGITS + 1)

#ifndef JSTR_CFG_HAVE_ALLOCA
#	define PJSTR_MIN_MMAP (128 * 1024)
#endif

#ifndef JSTR_CFG_HAVE_ALLOCA
#	define JSTR_CFG_HAVE_ALLOCA 1
#endif

#define JSTR_CFG_MIN_CAP 24

#ifndef JSTR_CFG_GROWTH_MULTIPLIER
#	define JSTR_CFG_GROWTH_MULTIPLIER 1.5
#endif

#ifndef JSTR_CFG_ALLOC_MULTIPLIER
#	define JSTR_CFG_ALLOC_MULTIPLIER 2
#endif

#ifndef JSTR_CFG_EXIT_ON_MALLOC_ERROR
#	define JSTR_CFG_EXIT_ON_MALLOC_ERROR 1
#endif

#ifndef JSTR_CFG_PRINT_ERR_MSG_ON_MALLOC_ERROR
#	define JSTR_CFG_PRINT_ERR_MSG_ON_MALLOC_ERROR 1
#endif

#ifndef JSTR_CFG_PRINT_ERR_MSG_ON_REGEX_ERROR
#	define JSTR_CFG_PRINT_ERR_MSG_ON_REGEX_ERROR 1
#endif

#ifndef JSTR_CFG_FREE_ON_DESTRUCTOR_CPP
#	define JSTR_CFG_FREE_ON_DESTRUCTOR_CPP 1
#endif

#ifndef JSTR_CFG_NULLIFY_PTR_ON_DESTRUCTOR_CPP
#	define JSTR_CFG_NULLIFY_PTR_ON_DESTRUCTOR_CPP 1
#endif

#ifndef JSTR_CFG_NULLIFY_PTR_ON_DELETE
#	define JSTR_CFG_NULLIFY_PTR_ON_DELETE 1
#endif

#if JSTR_CFG_FREE_ON_DESTRUCTOR_CPP
#	undef JSTR_CFG_NULLIFY_PTR_ON_DELETE
#	define JSTR_CFG_NULLIFY_PTR_ON_DELETE 1
#endif

#ifndef JSTR_CFG_GROWTH_MULTIPLIER
#	define JSTR_CFG_GROWTH_MULTIPLIER 2
#endif

#endif /* JSTR_CONFIG_DEF_H */
