#ifndef JSTR_H_DEF
#define JSTR_H_DEF

#include "_jregex.h"
#include "_builder.h"
#include "_config.h"
#include "_ctype.h"
#include "_io.h"
#include "_macros.h"
#include "_memmem.h"
#include "_replace.h"
#include "_string.h"

#undef JSTR_CFG_ALLOC_MULTIPLIER
#undef JSTR_ASCII_SIZE
#undef JSTR_CFG_EXIT_ON_MALLOC_ERROR
#undef JSTR_CFG_FREE_ON_DESTRUCTOR_CPP
#undef PRIV_JSTR_GROW
#undef JSTR_CFG_GROWTH_MULTIPLIER
#undef JSTR_HASH2
#undef JSTR_HASH2_LOWER
#undef JSTR_H_REPLACE_DEF
#undef JSTR_IS_CHAR
#undef JSTR_IS_MMAP
#undef JSTR_MAX_INT_DIGITS
#undef JSTR_MAX_LONG_DIGITS
#undef JSTR_MAX_LONG_LONG_DIGITS
#undef JSTR_MAX_UINT_DIGITS
#undef JSTR_MAX_ULONG_DIGITS
#undef JSTR_MAX_ULONG_LONG_DIGITS
#undef JSTR_MIN_MMAP
#undef JSTR_NEXT_POW2
#undef JSTR_CFG_NULLIFY_PTR_ON_DELETE
#undef JSTR_CFG_NULLIFY_PTR_ON_DELETE
#undef JSTR_CFG_NULLIFY_PTR_ON_DESTRUCTOR_CPP
#undef JSTR_CFG_PRINT_ERR_MSG_ON_MALLOC_ERROR
#undef JSTR_CFG_PRINT_ERR_MSG_ON_REGEX_ERROR
#undef PRIV_JSTR_REALLOC
#undef JSTR_RST
#undef JSTR_SAME_TYPE
#undef PRIV_JSTR_ALLOC_ONLY
#undef PRIV_JSTR_MEMMEM
#undef PRIV_JSTR_MEMMEMR
#undef PRIV_JSTR_MEMMEM_EXEC
#undef PRIV_JSTR_MIN_ALLOC
#undef PRIV_JSTR_STRSTRCASE

#endif /* JSTR_H_DEF */
