#!/bin/sh
DIR_CPP=cpp
DIR_C=c
for file in $(echo *.h*); do
	perl gen_func.pl "$file" &
done
wait
for file in $(echo $DIR_CPP/*.h*); do
	./fmt "$file" &
done
for file in $(echo $DIR_C/*.h*); do
	./fmt "$file" &
done
wait
# for file in $(echo $DIR_CPP/*.h*); do
# 	perl gen_skel.pl "$file" &
# done
# for file in $(echo $DIR_C/*.h*); do
# 	perl gen_skel.pl "$file" &
# done
# wait
