#!/bin/sh
DIR=cpp
FMT_FILE=.clang-format
for file in $(echo *.h*); do
	./gen_func.pl "$file" &
done
wait
for file in $(echo $DIR/*.h*); do
	clang-format -i --style=file:"$FMT_FILE" "$file" &
done
wait
