#!/bin/sh
cpp_dir=./cpp
namespace=jstr
namespace_cpt=JSTR
mkdir -p $cpp_dir
for fname in $(echo *.h); do
	newfname="cpp/$fname"pp
	printf "%s" "$(./gen_func.pl "$fname")" >>"$newfname" || exit
	printf "%s" "$(sed "s/$namespace_cpt\_EXTERN_C[ \t]\{1,\}1/$namespace_cpt\_EXTERN_C 0/;
	s/$namespace_cpt\_NAMESPACE[ \t]\{1,\}0/$namespace_cpt\_NAMESPACE 1/;
	s/H_DEF/HPP_DEF/;
	s/\.h\"/\.hpp\"/g;
	s/\($namespace\_[_0-9A-Za-z]\{1,\}\)mem/\1/g;
	s/_j(/(/g;" "$newfname")" >"$newfname" || exit
	echo "$newfname"
done
