#!/bin/sh
./clone_glibc
find . -type f -name 'string-*fz*' -o -name 'string-*shift*' -o -name 'string-*misc*' |
	sed 's/\(.*\)/\1 \1/; s/ .*sysdeps\/\(.*\)/ \1/; s/ \([^/]*\)\// \1-/ ;s/ \([^/]*\)\// \1-/' |
	while read -r lines; do
		cp -f $lines
	done
./tidy_glibc_funcs
