#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
for file in $(echo ./jstr/*.h); do
	{
		case "$file" in
		*_lgpl*.h | *_glibc*.h) rm "$file" && exit ;;
		esac
		#shellcheck disable=SC2005
		echo "$(perl ./remove-lgpl.pl "$file")" >"$file"
	} &
done
wait
