#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
for file in $(echo ./jstr/*.h); do
	{
		expr "$file" : '*_lgpl*.h' && rm "$file" && exit
		#shellcheck disable=SC2005
		echo "$(perl ./remove-lgpl.pl "$file")" >"$file"
	} &
done
wait
