#!/bin/sh
new=$1
new_upp=$(echo "$new" | tr '[:lower:]' '[:upper:]')
nmspc=jstr
nmspc_upp=$(echo $nmspc | tr '[:lower:]' '[:upper:]')
if ! test "$new"; then
	echo 'Usage: ./replace_nmspc <nmspc>'
	echo 'For example: ./replace_nmspc j'
	echo 'jstr -> j'
	exit
fi
new_name() { echo "$1" | sed "s/$nmspc\_/$new\_/"; }
for file in $(echo c/*.h); do
	{
		newfile=$(new_name "$file")
		sed "s/$nmspc\_/$new\_/g; s/$nmspc_upp\_/$new_upp\_/g" "$file" >"$newfile"
		./fmt "$newfile"
	} &
done
for file in $(echo cpp/*.h*); do
	{
		newfile=$(new_name "$file")
		sed "s/$nmspc\_/$new\_/g; s/$nmspc_upp\_/$new_upp\_/g; s/namespace $nmspc/namespace $new/g" "$file" >"$newfile"
		./fmt "$newfile"
	} &
done
wait
