#!/bin/sh
if ! test "$1"; then
	echo 'Usage: ./replace_namespace <namespace>'
	echo 'For example: ./replace_namespace j'
	echo 'jstd -> j'
	exit
fi
for file in $(echo c/*.h); do
	sed "s/jstd_/$1_/g" "$file" > "c/$1.h"
	echo "sed s/jstd_/$1_/g $file > c/$1.h"
done
