#!/bin/sh
namspac=jstr
namspac_upp=$(echo $namspac | tr '[:lower:]' '[:upper:]')
if ! test "$1"; then
	echo 'Usage: ./replace_namspac <namspac>'
	echo 'For example: ./replace_namspac j'
	echo 'jstr -> j'
	exit
fi
for file in $(echo c/*.h); do
	{
		sed "s/$namspac\_/$1_/g; s/$namspac_upp\_/$1_/g" "$file" >"c/$1.h"
		echo "sed s/$namspac\_/$1_/g; s/$namspac_upp\_/$1_/g $file > c/$1.h"
	} &
done
