#include "jstr_macros.h"
#if JSTR_ARCH_POWERPC
#	include "powerpc-string-fza.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#if JSTR_ARCH_ARM6T2
#	include "arm-armv6t2-string-fza.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#	include "generic-string-fza.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
