#if JSTR_ARCH_ALPHA
#	include "alpha-string-fzc.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#elif JSTR_ARCH_SH
#	include "sh-string-fzb.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#	include "generic-string-fzc.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
#include "jstr_macros.h"
