#!/bin/sh
for header in $(echo ./tests/*.c); do
	{
	basename=${header%.*}
	if ! test -e "$basename" || test "$basename" -ot "$header"; then
		cc "$header" -o "$basename"
	fi
	./"$basename"
	} &
done
wait
