#!/bin/sh
#shellcheck disable=disable=SC2086

FLAGS='
-g
-std=c99
-Wall
-Wextra
-Wpedantic
-Wsign-conversion
-DJSTR_TEST_SLOW=1
-DVERBOSE=1
'

USE_TCC=0

has_prog()
{
	type "$1" >/dev/null 2>/dev/null
}

compile()
{
	file=$1
	args=$(echo "$*" | cut -d' ' -f3-)
	if [ $CC = 'tcc' ]; then
		$CC $FLAGS $args -run "$file" $args
	else
		file=$1
		out=$2
		out=$out$(echo "$args" | tr -d ' ')
		$CC "$file" -o "$out" $FLAGS $args
		"$out"
		rm "$out"
	fi
}

cd "$(dirname "$0")" || exit

if [ $USE_TCC != 0 ] && has_prog tcc; then
	CC=tcc
else
	CC=cc
	# In GCC, -O1 compiles faster.
	[ "$(readlink "$(command -v cc)")" = 'gcc' ] && FLAGS="$FLAGS -O1"
	# Set the path to compile the tests to.
	if [ -z "$TMPDIR" ]; then
		if [ -d /tmp ]; then
			TMPDIR=/tmp
		else
			TMPDIR=$(echo "$PWD" | head -c 255)
		fi
	else
		TMPDIR=$TMPDIR/
	fi
	tmp="$TMPDIR"/$(echo "$PWD" | sed 's/\///g; s/\.//g')
	mkdir -p "$tmp"
fi


# Test all files in arguments. Otherwise, test all.
if [ $# -eq 0 ]; then
	files=$(echo *.c)
else
	files=$*
fi

for file in $files; do
	out_file=${file%.*}
	compile "$file" "$tmp$out_file" $FLAGS &
	compile "$file" "$tmp$out_file" $FLAGS -march=native &
done
wait

[ $CC != 'tcc' ] && rm -rf "$tmp"
