#!/bin/sh
#shellcheck disable=disable=SC2086

# Set the path to compile the tests to.
if [ -z "$TMPDIR" ]; then
	if [ -d /tmp ]; then
		TMPDIR=/tmp/$tmp
	else
		TMPDIR=$PWD/$tmp
	fi
else
	TMPDIR=$TMPDIR/
fi

tmp="$TMPDIR"__$(echo "$PWD" | sed 's/\///g; s/\.//g')
FLAGS='-march=native'

mkdir -p "$tmp"

# Test all files in arguments. Otherwise, test all.
if [ $# -eq 0 ]; then
	files=$(echo *.c)
else
	files=$*
fi

for file in $files; do
	{
	base=${file%.*}-exe
	#shellcheck disable=SC2086
	cc "$file" -o "$tmp/$base" $FLAGS
	} &
done
wait

for file in $(echo $tmp/*); do
	echo "Running $(echo ${file##*/} | sed 's/-[^-]*$//')"
	output=$($file)
	echo "$output"
	echo "$output" >"$(echo "$file" | sed 's/.*\//result-/; s/\-exe//')"
done

rm -rf "$tmp"
