#!/bin/sh

# In GCC, -O1 compiles faster.
[ "$(readlink "$(command -v cc)")" = 'gcc' ] && FLAGS="$FLAGS -O1"
# Set the path to compile the tests to.
if [ -z "$TMPDIR" ]; then
	if [ -d /tmp ]; then
		TMPDIR=/tmp/$tmp
	else
		TMPDIR=$PWD/$tmp
	fi
fi

tmp="$TMPDIR"__$(echo "$PWD" | sed 's/\///g; s/\.//g')

mkdir -p "$tmp"

for file in $(echo *.c); do
	{
	base=${file%.*}-exe
	cc "$file" -o "$tmp/$base" -O3 -march=native
	} &
done
wait
for file in $(echo "$tmp"/*-exe); do
	output=$($file)
	echo "$output"
	echo "$output" >"$(echo "$file" | sed 's/.*\//result-/;')"
done

rm -rf "$tmp"
