#!/bin/sh
#shellcheck disable=SC2086

# Run benchmarks in bench/. Usage: bench [file.c ...]
# Results are written to result-<name> files and printed.

cd "$(dirname "$0")" || exit

tmp="${TMPDIR:-/tmp}"/jstr-bench__$(echo "$PWD" | sed 's/\///g; s/\.//g')
FLAGS='-march=native -O2 -std=c99'
LIBS='-L../build/lib -ljstr'

rm -rf "$tmp"
mkdir -p "$tmp" || exit

# Test all files in arguments. Otherwise, all *.c sources.
if [ $# -eq 0 ]; then
	files=$(ls *.c)
else
	files=$*
fi

for file in $files; do
	{
	base=${file%.*}-exe
	if ! cc "$file" -o "$tmp/$base" $FLAGS $LIBS; then
		echo "COMPILE FAILED: $file" >&2
	fi
	} &
done
wait

LD_LIBRARY_PATH=../build/lib
export LD_LIBRARY_PATH

ret=0
for exe in "$tmp"/*-exe; do
	name=${exe##*/result-}
	name=$(basename "$exe")
	name=${name%-exe}
	echo "== $name =="
	output=$("$exe") || ret=1
	echo "$output"
	printf '%s\n' "$output" >"result-$name"
done

rm -rf "$tmp"
exit $ret
