#!/bin/sh
#shellcheck disable=SC2086,2068,2005,2028

PS4='' set -ex

CFLAGS='-Wall -Wextra -Wpedantic -Wsign-conversion -std=c99'
PATH_BUILD=../jstr
PATH_SRC=../include
PATH_MACROS=$PATH_BUILD/macros.h

mkdir -p $PATH_BUILD/internal
mkdir -p $PATH_BUILD/internal/musl

has_prog()
{
	type "$1" >/dev/null 2>/dev/null
}

update()
{
	in_fname=$1
	base_fname=$(basename $in_fname)
	case $in_fname in
	*/internal/musl/*.h)
		out_fname=$PATH_BUILD/internal/musl/$base_fname
		perl ./namespace-macros.pl "$in_fname" >"$out_fname"
		;;
	*/internal/*.h)
		out_fname=$PATH_BUILD/internal/$base_fname
		perl ./namespace-macros.pl "$in_fname" >"$out_fname"
		;;
	*/*macro*.h)
		out_fname=$PATH_BUILD/$base_fname
		perl ./namespace-macros.pl "$in_fname" >"$out_fname"
		;;
	*/*.h)
		out_fname=$PATH_BUILD/$base_fname
		perl ./gen-func.pl "$in_fname" | perl ./namespace-macros.pl >"$out_fname"
		;;
	*)
		cp -f "$in_fname" "$out_fname"
		;;
	esac
}

mark_as_built()
{
	mv "$PATH_MACROS" "$PATH_MACROS.bak"
	sed 's/\([ \t]*#[ \t]*ifndef[ \t]\{1,\}JSTR_BUILT\)/#define JSTR_BUILT\n\1/' "$PATH_MACROS.bak" >"$PATH_MACROS"
	rm "$PATH_MACROS.bak"
}

cd "$(dirname "$0")" || exit
./setup || exit
./clean
mkdir -p ../jstr

for file in $(find $PATH_SRC -type f); do
	update "$file" &
done
wait
mark_as_built

if has_prog tcc; then
	printf "#define JSTR_BUILT\n #include \"../jstr/jstr.h\"\n int main(){return 0;}\n" | tcc -run - || exit
else
	if [ -z "$TMPDIR" ]; then
		if [ -d /tmp ]; then
			TMPDIR=/tmp/$tmp
		else
			TMPDIR=$PWD/$tmp
		fi
	fi
	tmp="$TMPDIR"__$(echo "$PWD" | sed 's/\///g; s/\.//g')-
	cc ../jstr/jstr.h $CFLAGS -o "$tmp" || exit
	rm "$tmp"
fi
