#!/bin/sh

PS4='' set -e

undefine()
{
	#shellcheck disable=SC2005
	mv "$2" "$2.bak"
	python3 ../scripts-py/check_undefined_macros.py "$1" "$2.bak" >"$2"
	rm "$2.bak"
}

cd "$(dirname "$0")" || exit
undefine 'JSTR_' ../include/macros.h &
undefine 'JSTR_ARCH' ../include/macros-arch.h &
undefine 'JSTR_(?:OS|ENV)' ../include/macros-os.h &
wait
