#!/bin/sh

PS4='' set -ex

undefine()
{
	#shellcheck disable=SC2005
	mv "$2" "$2.bak"
	perl ./check-undefined-macros.pl "$1" "$2.bak" >"$2"
	rm "$2.bak"
}

cd "$(dirname "$0")" || exit
undefine 'JSTR_' ../include/macros.h &
undefine 'JSTR_ARCH' ../include/macros-arch.h &
undefine 'JSTR_(?:OS|ENV)' ../include/macros-os.h &
wait
