#!/bin/sh

set -e

undefine()
{
	#shellcheck disable=SC2005
	echo "$(perl ./check-undefined-macros.pl "$1" "$2")" >"$2"
}

cd "$(dirname "$0")" || exit
undefine 'JSTR_' ../include/macros.h &
undefine 'JSTR_ARCH' ../include/macros-arch.h &
undefine 'JSTR_(?:OS|ENV)' ../include/macros-os.h &
wait
