#!/bin/sh

cd "$(dirname "$0")" || exit
PATH_MACROS=../src/jstr-macros.h
echo "$(sed "s/#[ \t]*define[ \t]*JSTR_PAGE_SIZE.*/#define JSTR_PAGE_SIZE $(getconf PAGE_SIZE)/" "$PATH_MACROS")" > "$PATH_MACROS"
