#!/bin/sh
mkdir -p ../headers
files=$(find ../include/ -type f -name '*h' -a ! -name '.' -a ! -name '_*')
for file in $files; do
	echo "python3 ./gen-headers $file >> ../headers/$file.hh"
	python3 ../scripts-py/gen_headers.py "$file" >> ../headers/$file.hh &
done
wait
mv ../include/*.hh ../headers
