#!/usr/bin/perl
use strict;
use warnings;

# gen-lib.pl — convert generated jstr/ headers into non-static copies
# for shared/static library compilation.
#
# Copies headers into out/include/ WITH static/JSTR_API preserved so that
# cross-inclusions between module headers don't produce duplicate
# symbols at link time.
#
# For each MODULE header, creates a PRIVATE copy in out/private/<modname>/
# with ^JSTR_API stripped (the function body branch), so that the dedicated
# .c compilation unit emits non-static (exported) symbols.
#
# Compilation order: -iquote out/private/<mod> -iquote out/include
# ensures that a .c file picks up its own module's stripped copy first,
# while any other module headers it includes resolve to the static copy.

use File::Path qw(make_path);
use File::Copy qw(cp);

my $JSTR_DIR  = '../jstr';
my $BUILD_DIR = '../out';
my $SRC_DIR   = "$BUILD_DIR/src";
my $INC_DIR   = "$BUILD_DIR/include";
my $PRIV_DIR  = "$BUILD_DIR/private";
my $LIB_DIR   = "$BUILD_DIR/lib";

make_path($SRC_DIR);
make_path($INC_DIR);
make_path($PRIV_DIR);
make_path($LIB_DIR);

# Module headers — for each, a .c file is created AND static is stripped
# in the private copy.  All other headers (macros.h, internal/*, etc.)
# keep their original static keywords.
my %is_module = map { $_ => 1 } qw(
	builder.h string.h replace.h regex.h io.h
	ctype.h itoa.h stdstring.h struct.h
);

# --- 1. Copy ALL headers to out/include/, static preserved ---------------

sub copy_tree {
	my ($src_dir, $dst_dir) = @_;
	opendir(my $dh, $src_dir) or die "Cannot open $src_dir: $!";
	while (my $entry = readdir($dh)) {
		next if $entry eq '.' || $entry eq '..';
		my $src_path  = "$src_dir/$entry";
		my $dst_path  = "$dst_dir/$entry";
		if (-d $src_path) {
			make_path($dst_path);
			copy_tree($src_path, $dst_path);
		} elsif ($entry =~ /\.h$/) {
			cp($src_path, $dst_path) or die "Cannot copy $src_path -> $dst_path: $!";
		}
	}
	closedir($dh);
}

copy_tree($JSTR_DIR, $INC_DIR);

# --- 2. Per-module private copies with ^static stripped ------------------

for my $hdr (sort keys %is_module) {
	(my $mod = $hdr) =~ s/\.h$//;
	my $mod_priv_dir = "$PRIV_DIR/$mod";
	make_path($mod_priv_dir);

	my $src_path = "$JSTR_DIR/$hdr";
	my $dst_path = "$mod_priv_dir/$hdr";
	open(my $sfh, '<', $src_path) or die "Cannot read $src_path: $!";
	open(my $dfh, '>', $dst_path) or die "Cannot write $dst_path: $!";
	while (my $line = <$sfh>) {
		if ($line =~ /^JSTR_API /) {
			$line =~ s/^JSTR_API //;
		}
		print $dfh $line;
	}
	close($sfh);
	close($dfh);
}

# --- 3. One .c file per module header ------------------------------------

for my $hdr (sort keys %is_module) {
	(my $c_name = $hdr) =~ s/\.h$/.c/;
	open(my $cfh, '>', "$SRC_DIR/$c_name") or die "Cannot write $SRC_DIR/$c_name: $!";
	print $cfh "/* Generated by gen-lib.pl -- do not edit. */\n";
	print $cfh "#include \"$hdr\"\n";
	close($cfh);
}
