#!/bin/sh

PS4='' set -e

#shellcheck disable=SC2068
cd "$(dirname "$0")" || exit

INSTALL_DIR='/usr/local'

[ $# -eq 1 ] && INSTALL_DIR=$1
if [ "$(id -u)" -eq 0 ]; then
	cp -rf '../build/include' "$INSTALL_DIR"
	cp -rf '../build/lib' "$INSTALL_DIR"
	echo "Successfully built to $INSTALL_DIR."
	if [ "$INSTALL_DIR" = '/usr/local' ]; then
		sudo ln -s /usr/local/lib/libjstr.so /usr/lib
	fi
else
	echo "Please run the command with sudo, as it requires permission to install to /usr/local/"
	exit 1
fi
