#!/bin/sh
#shellcheck disable=disable=SC2086

set -e

echo 'This might take a while...'

PATH_TEST=../tests

CFLAGS="
-g
-std=c99
-Wall
-Wextra
-Wpedantic
-O2
-fsanitize=address
$CFLAGS
"

has_prog()
{
	type "$1" >/dev/null 2>/dev/null
}

compile_and_run()
{
	file=$1
	out=$2
	shift
	shift
	args=$*
	out=$out$(echo "$args" | tr -d ' ')
	nice -n 19 cc "$file" -o "$out" $args
	out_clean=$(basename $out)
	if nice -n 19 "$out"; then
		echo "PASS: $out_clean"
	else
		echo "FAIL: $out_clean"
	fi
	rm "$out"
}

cd "$(dirname "$0")" || exit

# Set the path to compile_and_run the tests to.
if [ -z "$TMPDIR" ]; then
	if [ -d /tmp ]; then
		TMPDIR=/tmp
	else
		TMPDIR=$(echo "$PWD" | head -c 255)
	fi
fi
tmp="$TMPDIR"/$(echo "$PWD" | sed 's/\///g; s/\.//g')
mkdir "$tmp" || exit

# Test all files in arguments. Otherwise, test all.
if [ $# -eq 0 ]; then
	files=$(echo $PATH_TEST/*.c)
else
	files=$*
fi

# Fast tests
for file in $files; do
	out_file=$(echo ${file%.*} | sed 's/^.*\/// ;s/\.//g; s/\/\//\//g')
	compile_and_run "$file" "$tmp/$out_file" $CFLAGS &
	compile_and_run "$file" "$tmp/$out_file" $CFLAGS -march=native &
done
wait

# Slow tests
for file in $files; do
	out_file=$(echo ${file%.*} | sed 's/^.*\/// ;s/\.//g; s/\/\//\//g')
	compile_and_run "$file" "$tmp/$out_file" $CFLAGS -DJSTR_TEST_SLOW=1 &
	compile_and_run "$file" "$tmp/$out_file" $CFLAGS -DJSTR_TEST_SLOW=1 -march=native &
done
wait

rmdir "$tmp"
