#!/bin/sh
#shellcheck disable=disable=SC2086

PATH_TEST=../tests

CFLAGS="
-g
-std=c99
-Wall
-Wextra
-Wpedantic
-DJSTR_TEST_SLOW=1
-O2
-U__SSE2__
$CFLAGS
"

has_prog()
{
	type "$1" >/dev/null 2>/dev/null
}

compile()
{
	file=$1
	args=$(echo "$*" | cut -d' ' -f3-)
	file=$1
	out=$2
	out=$out$(echo "$args" | tr -d ' ')
	$CC "$file" -o "$out" $CFLAGS $args
	"$out"
	rm "$out"
}

cd "$(dirname "$0")" || exit

CC="$(readlink "$(command -v cc)")"
# Set the path to compile the tests to.
if [ -z "$TMPDIR" ]; then
	if [ -d /tmp ]; then
		TMPDIR=/tmp
	else
		TMPDIR=$(echo "$PWD" | head -c 255)
	fi
fi
tmp="$TMPDIR"/$(echo "$PWD" | sed 's/\///g; s/\.//g')
mkdir -p "$tmp"
echo 'This might take a while.'

# Test all files in arguments. Otherwise, test all.
if [ $# -eq 0 ]; then
	files=$(echo $PATH_TEST/*.c)
else
	files=$*
fi

for file in $files; do
	out_file=$(echo ${file%.*} | sed 's/^.*\/// ;s/\.//g; s/\/\//\//g')
	compile "$file" "$tmp/$out_file" $CFLAGS &
	compile "$file" "$tmp/$out_file" $CFLAGS -march=native &
done
wait

rm -rf "$tmp"
