#!/bin/sh
update_if_needed()
{
	if [ -e ../jstr/"$1" ]; then
		test "$1" -ot ../jstr/"$1" && exit 0
	fi
	perl generate-func.pl "$1" >../jstr/"$1"
	echo "Built $1."
}
mkdir -p ../jstr
for file in $(echo *.h | tr ' ' '\n' | grep -v 'glibc'); do
	update_if_needed "$file" &
done &
./update-glibc
for file in $(echo glibc-*.h); do
	update_if_needed "$file" &
done &
wait
