#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
./setup || exit
mkdir -p ../jstr
cp ../LICENSE ../jstr 2>/dev/null
update_if_needed()
{
	in_fname=$1
	out_fname=../jstr/$in_fname
	test -e "$out_fname" &&
		test "$in_fname" -ot "$out_fname" && exit 0
	if [ "$in_fname" = 'jstr-macros.h' ] || expr "$in_fname" : '^_' >/dev/null; then
		cp -f "$in_fname" "$out_fname"
	else
		perl ./gen-func.pl "$in_fname" >"$out_fname"
	fi
	echo "Built $in_fname."
}
for file in $(echo *.h); do
	update_if_needed "$file" &
done
wait
compile()
{
	file=$1
	shift
	#shellcheck disable=SC2068
	cc -x c -o $@ -
}
file_str='#include "../jstr/jstr.h"
int main(void) {return 0;}'
TMP=/tmp/__jstr_tmp_obj__
echo "$file_str" | compile "$TMP" || exit &
echo "$file_str" | compile "$TMP" -D__STRICT_ANSI__ || exit &
echo "$file_str" | compile "$TMP" -DJSTR_USE_LGPL=0 || exit &
wait
rm -f $TMP
