#!/bin/sh

verbose()
{
	echo "$*"
	#shellcheck disable=2068
	$@
}

has_prog()
{
	type "$1" >/dev/null 2>/dev/null
}

update_if_needed()
{
	in_fname=$1
	out_fname=../jstr/$in_fname
	test -e "$out_fname" && test "$in_fname" -ot "$out_fname" && exit 0
	case $in_fname in
	*macro*) ;;
	*_jstr-*)
		perl ./namespace-macros.pl "$in_fname" >"$out_fname"
		echo "perl ./namespace-macros.pl $in_fname >$out_fname"
		exit 0
		;;
	*jstr-*)
		perl ./gen-func.pl "$in_fname" | perl ./namespace-macros.pl >"$out_fname"
		echo "perl ./gen-func.pl $in_fname | perl ./namespace-macros.pl >$out_fname"
		exit 0
		;;
	*) ;;
	esac
	verbose cp -f "$in_fname" "$out_fname"
}

mark_as_built()
{
	#shellcheck disable=SC2005
	echo "$(sed 's/\([ \t]*#[ \t]*ifndef[ \t]\{1,\}JSTR_BUILT\)/#define JSTR_BUILT\n\1/' ../jstr/jstr-macros.h)" >../jstr/jstr-macros.h
}

cd "$(dirname "$0")" || exit
./setup || exit
./test || exit
mkdir -p ../jstr

for file in $(echo *.h); do
	update_if_needed "$file" &
done
wait
mark_as_built

FLAGS='-Wall -Wextra -Wpedantic -std=c99'
if has_prog tcc; then
	printf "#define JSTR_BUILT\n #include \"jstr.h\"\n int main(){return 0;}\n" | tcc -run -
else
	if [ -z "$TMPDIR" ]; then
		if [ -d /tmp ]; then
			TMPDIR=/tmp/$tmp
		else
			TMPDIR=$PWD/$tmp
		fi
	fi
	tmp="$TMPDIR"__$(echo "$PWD" | sed 's/\///g; s/\.//g')-
	#shellcheck disable=SC2086
	verbose cc ../jstr/jstr.h $FLAGS -o "$tmp" || exit
	rm "$tmp"
fi
echo 'Built to jstr.'
