#!/bin/sh
update_if_needed()
{
	if [ -e ../jstr/"$1" ]; then
		test "$1" -ot ../jstr/"$1" && exit 0
	fi
}
perl generate-func.pl "$file" > ../jstr/"$file"
for file in $(echo j*.h); do
	update_if_needed "$file" &
done &
./tidy-glibc || exit 0
for file in $(echo *-string-*.h); do
	update_if_needed "$file" &
done
