#!/bin/sh
update_if_needed()
{
	out_fname=../jstr/$1
	test -e "$out_fname" &&
		test "$1" -ot "$out_fname" && exit 0
	perl generate-func.pl "$1" >"$out_fname"
	echo "Built $1."
}
mkdir -p ../jstr
for file in $(echo *.h | tr ' ' '\n' | grep -v 'glibc'); do
	update_if_needed "$file" &
done &
./update-glibc
for file in $(echo glibc-*.h); do
	update_if_needed "$file" &
done &
wait
