#!/bin/sh

# Copyright (c) 2023 James Tirta Halim <tirtajames45 at gmail dot com>
# This file is part of the jstring library.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# MIT License (Expat)

cd "$(dirname "$0")" || exit
./setup || exit
mkdir -p ../jstr
update_if_needed()
{
	in_fname=$1
	out_fname=../jstr/$in_fname
	test -e "$out_fname" && test "$in_fname" -ot "$out_fname" && exit 0
	case $in_fname in
	*macro*) ;;
	*_jstr*) perl ./namespace-macros.pl "$in_fname" > "$out_fname";;
	*jstr-*)
		perl ./gen-func.pl "$in_fname" | perl ./namespace-macros.pl >"$out_fname"
		exit 0
		;;
	*) ;;
	esac
	cp -f "$in_fname" "$out_fname"
}
for file in $(echo *.h); do
	update_if_needed "$file" &
done
wait
compile()
{
	file=$1
	shift
	#shellcheck disable=SC2068
	cc -x c $@ -o "$file" -
}
file_str='#include "../jstr/jstr.h"
int main(void) {return 0;}'
TMP=/tmp/__jstr_tmp_obj__
echo "$file_str" | compile "$TMP" || exit &
echo "$file_str" | compile "$TMP" -D__STRICT_ANSI__ || exit &
echo "$file_str" | compile "$TMP" -DJSTR_USE_LGPL=0 || exit &
wait
rm -f $TMP
