#!/bin/sh

undefine()
{
	#shellcheck disable=SC2005
	echo "$(perl ./check-undefined-macros.pl "$1" "$2")" >"$2"
}

cd "$(dirname "$0")" || exit
undefine 'JSTR_' ./jstr-macros.h &
undefine 'JSTR_ARCH' ./jstr-macros-arch.h &
undefine 'JSTR_OS' ./jstr-macros-os.h &
wait
