#!/bin/sh

undefine()
{
	#shellcheck disable=SC2005
	echo "$(perl ./check-undefined-macros.pl "$1" "$2")" >"$2"
}

cd "$(dirname "$0")" || exit
perl ./check-undefined-macros.pl 'JSTR_' ./jstr-macros.h &
perl ./check-undefined-macros.pl 'JSTR_ARCH' ./jstr-macros-arch.h &
perl ./check-undefined-macros.pl 'JSTR_OS' ./jstr-macros-os.h &
