#!/usr/bin/perl
use strict;
use warnings;

do "./jlib.pl";
my $file_str = '';

while (glob('_string-*.h')) {
	$file_str .= jl_file_get_str(\$_);
}

while (glob('_glibc-*.h')) {
	die "$_ isn't included in any _string-* file.\n" if (index($file_str, $_) == -1);
}
