#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
echo "$(sed "s/#[ \t]*define[ \t]*JSTR_PAGE_SIZE.*/#define JSTR_PAGE_SIZE $(getconf PAGE_SIZE)/" ./jstr-macros.h)" > ./jstr-macros.h
