#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
[ -e ../bin/is-little-endian ] || ../bin/build
# shellcheck disable=SC2005
[ "$(../bin/is-little-endian)" = 1 ] && echo "$(sed 's/^#[ \t]*define[ \t]*JSTR_ENDIAN_LITTLE.*$/#define JSTR_ENDIAN_LITTLE 1/' ./jstr-config.h)" >./jstr-config.h
