#!/bin/sh
fmt()
{
	clang-format -i --style=file:".clang-format" "$1"
}
fmt_if_needed()
{
	case $1 in
	*_pp_*) ;;
	*) fmt "$1" & ;;
	esac
}
for f in $(echo *.h *.c); do
	fmt_if_needed "$f" &
done
wait
