#!/bin/sh
cd "$(dirname "$0")" || exit
if ! type clang-format >/dev/null; then
	echo 'clang-format does not exist.'
	exit
fi
for file in $@; do
	{
		expr "$file" : '*-pp-*' >/dev/null && exit
		[ "$file" = 'jstr-macros.h' ] && exit
		clang-format -i --style=file:'.clang-format' "$file"
	} &
done
wait
