#!/bin/sh
cd "$(dirname "$0")" || exit
for f in $(echo *.h); do
	{
		expr "$f" : '*-pp-*' >/dev/null && exit
		[ "$f" = 'jstr-macros.h' ] && exit
		clang-format -i --style=file:".clang-format" "$f"
	} &
done
wait
