/* Copyright (c) 2023 James Tirta Halim <tirtajames45 at gmail dot com>
   This file is part of the jstring library.

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.

   MIT License (Expat) */

#ifndef JSTR_RAREBYTE_H
#define JSTR_RAREBYTE_H

#include "jstr-ctype-table.h"
#include "jstr-macros.h"

PJSTR_BEGIN_DECLS

typedef enum {
	JSTR_RAREBYTE_NUL = 0,
	JSTR_RAREBYTE_GENERIC,
	JSTR_RAREBYTE_UPPER,
	JSTR_RAREBYTE_DIGIT,
	JSTR_RAREBYTE_EXTENDEDASCII,
	JSTR_RAREBYTE_NONCHARACTER,
	JSTR_RAREBYTE_SYMBOL,
	JSTR_RAREBYTE_END
} jstr_rarebyte_ty;

/* Do not pass a non-unsigned char. */
JSTR_MAYBE_UNUSED
static const unsigned char jstr_rarebyte_table[256] = {
	JSTR_RAREBYTE_NUL, /* 0 */
	JSTR_RAREBYTE_NONCHARACTER, /* 1 */
	JSTR_RAREBYTE_NONCHARACTER, /* 2 */
	JSTR_RAREBYTE_NONCHARACTER, /* 3 */
	JSTR_RAREBYTE_NONCHARACTER, /* 4 */
	JSTR_RAREBYTE_NONCHARACTER, /* 5 */
	JSTR_RAREBYTE_NONCHARACTER, /* 6 */
	JSTR_RAREBYTE_NONCHARACTER, /* 7 */
	JSTR_RAREBYTE_NONCHARACTER, /* 8 */
	JSTR_RAREBYTE_NONCHARACTER, /* 9 */
	JSTR_RAREBYTE_NONCHARACTER, /* 10 */
	JSTR_RAREBYTE_NONCHARACTER, /* 11 */
	JSTR_RAREBYTE_NONCHARACTER, /* 12 */
	JSTR_RAREBYTE_NONCHARACTER, /* 13 */
	JSTR_RAREBYTE_NONCHARACTER, /* 14 */
	JSTR_RAREBYTE_NONCHARACTER, /* 15 */
	JSTR_RAREBYTE_NONCHARACTER, /* 16 */
	JSTR_RAREBYTE_NONCHARACTER, /* 17 */
	JSTR_RAREBYTE_NONCHARACTER, /* 18 */
	JSTR_RAREBYTE_NONCHARACTER, /* 19 */
	JSTR_RAREBYTE_NONCHARACTER, /* 20 */
	JSTR_RAREBYTE_NONCHARACTER, /* 21 */
	JSTR_RAREBYTE_NONCHARACTER, /* 22 */
	JSTR_RAREBYTE_NONCHARACTER, /* 23 */
	JSTR_RAREBYTE_NONCHARACTER, /* 24 */
	JSTR_RAREBYTE_NONCHARACTER, /* 25 */
	JSTR_RAREBYTE_NONCHARACTER, /* 26 */
	JSTR_RAREBYTE_NONCHARACTER, /* 27 */
	JSTR_RAREBYTE_NONCHARACTER, /* 28 */
	JSTR_RAREBYTE_NONCHARACTER, /* 29 */
	JSTR_RAREBYTE_NONCHARACTER, /* 30 */
	JSTR_RAREBYTE_NONCHARACTER, /* 31 */
	JSTR_RAREBYTE_SYMBOL, /* ' ' */
	JSTR_RAREBYTE_SYMBOL, /* '!' */
	JSTR_RAREBYTE_SYMBOL, /* '"' */
	JSTR_RAREBYTE_SYMBOL, /* '#' */
	JSTR_RAREBYTE_SYMBOL, /* '$' */
	JSTR_RAREBYTE_SYMBOL, /* '%' */
	JSTR_RAREBYTE_SYMBOL, /* '&' */
	JSTR_RAREBYTE_SYMBOL, /* '\'' */
	JSTR_RAREBYTE_SYMBOL, /* '(' */
	JSTR_RAREBYTE_SYMBOL, /* ')' */
	JSTR_RAREBYTE_SYMBOL, /* '*' */
	JSTR_RAREBYTE_SYMBOL, /* '+' */
	JSTR_RAREBYTE_SYMBOL, /* '', */
	JSTR_RAREBYTE_SYMBOL, /* '-' */
	JSTR_RAREBYTE_SYMBOL, /* '.' */
	JSTR_RAREBYTE_SYMBOL, /* '/' */
	JSTR_RAREBYTE_DIGIT, /* '0' */
	JSTR_RAREBYTE_DIGIT, /* '1' */
	JSTR_RAREBYTE_DIGIT, /* '2' */
	JSTR_RAREBYTE_DIGIT, /* '3' */
	JSTR_RAREBYTE_DIGIT, /* '4' */
	JSTR_RAREBYTE_DIGIT, /* '5' */
	JSTR_RAREBYTE_DIGIT, /* '6' */
	JSTR_RAREBYTE_DIGIT, /* '7' */
	JSTR_RAREBYTE_DIGIT, /* '8' */
	JSTR_RAREBYTE_DIGIT, /* '9' */
	JSTR_RAREBYTE_SYMBOL, /* ':' */
	JSTR_RAREBYTE_SYMBOL, /* ';' */
	JSTR_RAREBYTE_SYMBOL, /* '<' */
	JSTR_RAREBYTE_SYMBOL, /* '=' */
	JSTR_RAREBYTE_SYMBOL, /* '>' */
	JSTR_RAREBYTE_SYMBOL, /* '?' */
	JSTR_RAREBYTE_SYMBOL, /* '@' */
	JSTR_RAREBYTE_UPPER, /* 'A' */
	JSTR_RAREBYTE_UPPER, /* 'B' */
	JSTR_RAREBYTE_UPPER, /* 'C' */
	JSTR_RAREBYTE_UPPER, /* 'D' */
	JSTR_RAREBYTE_UPPER, /* 'E' */
	JSTR_RAREBYTE_UPPER, /* 'F' */
	JSTR_RAREBYTE_UPPER, /* 'G' */
	JSTR_RAREBYTE_UPPER, /* 'H' */
	JSTR_RAREBYTE_UPPER, /* 'I' */
	JSTR_RAREBYTE_UPPER, /* 'J' */
	JSTR_RAREBYTE_UPPER, /* 'K' */
	JSTR_RAREBYTE_UPPER, /* 'L' */
	JSTR_RAREBYTE_UPPER, /* 'M' */
	JSTR_RAREBYTE_UPPER, /* 'N' */
	JSTR_RAREBYTE_UPPER, /* 'O' */
	JSTR_RAREBYTE_UPPER, /* 'P' */
	JSTR_RAREBYTE_UPPER, /* 'Q' */
	JSTR_RAREBYTE_UPPER, /* 'R' */
	JSTR_RAREBYTE_UPPER, /* 'S' */
	JSTR_RAREBYTE_UPPER, /* 'T' */
	JSTR_RAREBYTE_UPPER, /* 'U' */
	JSTR_RAREBYTE_UPPER, /* 'V' */
	JSTR_RAREBYTE_UPPER, /* 'W' */
	JSTR_RAREBYTE_UPPER, /* 'X' */
	JSTR_RAREBYTE_UPPER, /* 'Y' */
	JSTR_RAREBYTE_UPPER, /* 'Z' */
	JSTR_RAREBYTE_SYMBOL, /* '[' */
	JSTR_RAREBYTE_SYMBOL, /* '\\' */
	JSTR_RAREBYTE_SYMBOL, /* ']' */
	JSTR_RAREBYTE_SYMBOL, /* '^' */
	JSTR_RAREBYTE_SYMBOL, /* '_' */
	JSTR_RAREBYTE_SYMBOL, /* '`' */
	0, /* 'a' */
	0, /* 'b' */
	0, /* 'c' */
	0, /* 'd' */
	0, /* 'e' */
	0, /* 'f' */
	0, /* 'g' */
	0, /* 'h' */
	0, /* 'i' */
	1, /* 'j' */
	0, /* 'k' */
	0, /* 'l' */
	0, /* 'm' */
	0, /* 'n' */
	0, /* 'o' */
	0, /* 'p' */
	1, /* 'q' */
	0, /* 'r' */
	0, /* 's' */
	0, /* 't' */
	0, /* 'u' */
	0, /* 'v' */
	0, /* 'w' */
	1, /* 'x' */
	0, /* 'y' */
	1, /* 'z' */
	JSTR_RAREBYTE_SYMBOL, /* '{' */
	JSTR_RAREBYTE_SYMBOL, /* '|' */
	JSTR_RAREBYTE_SYMBOL, /* '}' */
	JSTR_RAREBYTE_SYMBOL, /* '~' */
	JSTR_RAREBYTE_NONCHARACTER, /* 127 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 128 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 129 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 130 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 131 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 132 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 133 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 134 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 135 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 136 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 137 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 138 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 139 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 140 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 141 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 142 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 143 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 144 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 145 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 146 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 147 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 148 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 149 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 150 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 151 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 152 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 153 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 154 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 155 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 156 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 157 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 158 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 159 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 160 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 161 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 162 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 163 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 164 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 165 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 166 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 167 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 168 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 169 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 170 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 171 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 172 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 173 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 174 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 175 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 176 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 177 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 178 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 179 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 180 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 181 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 182 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 183 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 184 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 185 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 186 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 187 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 188 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 189 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 190 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 191 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 192 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 193 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 194 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 195 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 196 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 197 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 198 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 199 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 200 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 201 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 202 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 203 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 204 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 205 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 206 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 207 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 208 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 209 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 210 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 211 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 212 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 213 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 214 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 215 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 216 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 217 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 218 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 219 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 220 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 221 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 222 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 223 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 224 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 225 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 226 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 227 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 228 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 229 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 230 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 231 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 232 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 233 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 234 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 235 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 236 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 237 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 238 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 239 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 240 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 241 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 242 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 243 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 244 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 245 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 246 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 247 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 248 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 249 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 250 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 251 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 252 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 253 */
	JSTR_RAREBYTE_EXTENDEDASCII, /* 254 */
	JSTR_RAREBYTE_EXTENDEDASCII /* 255 */
};

JSTR_FUNC_PURE
JSTR_ATTR_INLINE
static void *
jstr_rarebyteget_len(const void *ne,
                     size_t n)
{
	int c;
	const unsigned char *p = (const unsigned char *)ne;
	for (; n-- && (c = *p); ++p)
		if (jstr_rarebyte_table[c])
			return (unsigned char *)p;
	return NULL;
}

JSTR_FUNC_PURE
JSTR_ATTR_INLINE
static char *
jstr_rarebyteget(const char *n)
{
	const unsigned char *p = (const unsigned char *)n;
	int c;
	for (; (c = *p); ++p)
		if (jstr_rarebyte_table[c])
			return (char *)p;
	return NULL;
}

JSTR_FUNC_PURE
JSTR_ATTR_INLINE
static char *
jstr_rarebytegetcase(const char *n)
{
	const unsigned char *p = (const unsigned char *)n;
	int c;
	for (; (c = *p); ++p)
		if (jstr_ctype_table[c] & (JSTR_ISDIGIT | JSTR_ISPUNCT))
			return (char *)p;
	return NULL;
}

JSTR_FUNC_PURE
JSTR_ATTR_INLINE
static char *
jstr_rarebytegetcase_len(const void *ne,
                         size_t n)
{
	const unsigned char *p = (const unsigned char *)ne;
	int c;
	for (; n-- && (c = *p); ++p)
		if (jstr_ctype_table[c] & (JSTR_ISDIGIT | JSTR_ISPUNCT))
			return (char *)p;
	return NULL;
}

PJSTR_END_DECLS

#endif /* JSTR_RAREBYTE_H */
