#!/bin/sh

cd "$(dirname "$0")" || exit
../scripts/build || exit
./check-little-endian || exit
./check-page-size || exit
# ./check-builtins || exit
# ./check-word-at-a-time-inclusion || exit
./check-undefined-macros || exit
./check-scoped-macros || exit
