#!/bin/sh

# See LICENSE file for copyright and license details.

cd "$(dirname "$0")" || exit
../bin/build
./check-little-endian
./check-page-size
./check-builtins || exit
./check-word-at-a-time-inclusion || exit
