#!/bin/sh
for file in $(echo glibc-*.h); do
	# shellcheck disable=SC2005
	echo "$(sed '
	s/#[ \t]*include[ \t]*<\(.*string.*\)>/#include "\1"/g;
	s/\(^\|[^_0-9A-Za-z]\)find_t\($\|[^_0-9A-Za-z]\)/\1jstr_word_ty\2/g;
	s/\(^\|[^_0-9A-Za-z]\)op_t\($\|[^_0-9A-Za-z]\)/\1jstr_word_ty\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(repeat_bytes\)\($\|[^_0-9A-Za-z]\)/\1jstr_word_\2\3/g;
	s/\(^\|[^_0-9A-Za-z]\)\(extractbyte\)\($\|[^_0-9A-Za-z]\)/\1jstr_word_\1\2\3/g;
	s/\(^\|[^_0-9A-Za-z]\)\(shift_\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(find_..\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(index_\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(has_\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(clz\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)\(ctz\)/\1jstr_word_\2/g;
	s/\(^\|[^_0-9A-Za-z]\)_Bool\($\|[^_0-9A-Za-z]\)/\1int\2/g;
	s/\(^\|[^_0-9A-Za-z]\)OP_T_THRES\($\|[^_0-9A-Za-z]\)/\1JSTR_WORD_THRES\2/g;
	s/typedef jstr_word_ty jstr_word_ty;//g;
	s/__always_inline/JSTR_INLINE/g;
	s/sysdeps\/generic\///;
	s/\(#define.*\)/\1\n\n#include "jstr-macros.h"\n/;
	s/#ifndef[ \t]*\([^P ][^J][^S][^T][^R][_A-Za-z0-9]*_H\)/#ifndef P_JSTR_\1/g;
	s/#define[ \t]*\([^P ][^J][^S][^T][^R][_A-Za-z0-9]*_H\)/#define P_JSTR_\1/g;
	s/P_JSTR__/P_JSTR_/g;
	s/if (__BYTE_ORDER == __LITTLE_ENDIAN)/if (JSTR_ENDIAN_LITTLE)/g;
	s/include[ \t]*"string\-/include "jstr-string-/g;
	s/__attribute__((__may_alias__))/JSTR_MAY_ALIAS/g;
	s/__attribute__((may_alias))/JSTR_MAY_ALIAS/g;
	' "$file")" >"$file" &
done
wait
for file in $(echo glibc-*.h); do
	# shellcheck disable=SC2005
	echo "$(awk '
	BEGIN {
		dup = 0
	}
	$0 != "" {
		if ($0 ~ /jstr-macros\.h/) {
			if (dup)
				next
			dup = 1
		}
		print
	}
	' "$file")" >"$file" &
done
wait
